server:
  port: 8080

spring:
  application:
    name: SpringSigecopGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Rutas del microservicio en localhost:9090
        - id: categoria
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/categoria/**

        - id: producto
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/producto/**

        - id: proveedor
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/proveedor/**

        - id: tipo-internamiento
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/tipoInternamiento/**

        # Rutas del microservicio en localhost:9091
        - id: session
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/session/**

        - id: pagina
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/pagina/**

        - id: permiso
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/permiso/**

        - id: rol
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/rol/**

        - id: usuario
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/usuario/**

        # Rutas del microservicio en localhost:9092
        - id: cotizacion
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/cotizacion/**

        - id: estadosolicitud
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/estado_solicitud/**

        - id: solicitud
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/solicitud/**

eureka:
  client:
    register-with-eureka: false
